[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "1"
regex = "1"
indicatif = {version = "0.17.7", features = ["rayon"]}
rayon = "1.8.0"
